projects:
  api:
    schemaPath: packages/api/schema.graphql
    includes: ['**/*.graphql']
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: prisma/generated/prisma.graphql
    includes: ['**/*.graphql']
    extensions:
      prisma: prisma/prisma.yml
